import "server-only";
import { IS_PRODUCTION_SITE } from "./site";

/**
 * Staging drafts — copy edited in the browser, held until Notion catches up.
 *
 * Notion is the source of truth and stays that way: a save writes there first
 * and only then lands here. What this store buys is the gap in between. The
 * site's copy reaches a page through `lib/events.generated.json`, which is
 * regenerated by the next requested sync and committed — so without somewhere to put
 * an edit, "save" would mean waiting for a sync and a redeploy before you could
 * see your own sentence. A draft is read on every staging request, so the page
 * shows it at once.
 *
 * It is deliberately a cache of a decision already recorded elsewhere, not a
 * second source of truth. When the sync next runs, the JSON catches up and the
 * draft becomes a copy of what the page would render anyway; `isStale()` is how
 * the editor spots that and clears it.
 *
 * PRODUCTION HAS NO KV BINDING AT ALL. Not a flag that could be flipped, not a
 * namespace that happens to be empty — `wrangler.jsonc` declares `DRAFTS` on the
 * staging Worker and not in the `production` environment, so the apex cannot
 * read a draft even if this module were called there. The `IS_PRODUCTION_SITE`
 * guard below is the second lock, not the only one.
 */

/**
 * Just the three methods used here.
 *
 * `@cloudflare/workers-types` would supply the real one, but it is not a
 * dependency and pulling it in to name three methods would put a second, older
 * set of DOM and fetch globals into the same tsconfig as Next's — which is a
 * well-worn way to get `Response` and `Headers` quietly disagreeing with
 * themselves across the app. `wrangler types` remains available via
 * `npm run cf-typegen` for anyone who wants the full surface.
 */
type KVNamespace = {
  get<T>(key: string, type: "json"): Promise<T | null>;
  put(key: string, value: string): Promise<void>;
  delete(key: string): Promise<void>;
};

export type EventDraft = {
  /** The event body for one locale, in Notion's own source form. */
  description: string;
  /** Cover `src` → alt text, for that locale. Absent keys keep what shipped. */
  alts: Record<string, string>;
  /** ISO timestamp, shown in the editor so a stale draft is visible as stale. */
  savedAt: string;
  /** Who saved it, if the passphrase holder gave a name. Free text. */
  by?: string;
};

const key = (slug: string, locale: string) => `event:${slug}:${locale}`;

/**
 * The KV namespace, or null when there isn't one.
 *
 * Null is a normal answer, not a failure: production never binds DRAFTS, and
 * neither does `next dev` or a Storybook build. Every caller treats null as
 * "no drafts exist", which is exactly right in all three cases.
 */
async function store(): Promise<KVNamespace | null> {
  if (IS_PRODUCTION_SITE) return null;
  try {
    const { getCloudflareContext } = await import("@opennextjs/cloudflare");
    const { env } = await getCloudflareContext({ async: true });
    return (env as { DRAFTS?: KVNamespace }).DRAFTS ?? null;
  } catch {
    // Not running inside a Worker — `next dev`, a unit test, a Storybook build.
    return null;
  }
}

export async function readDraft(slug: string, locale: string): Promise<EventDraft | null> {
  const kv = await store();
  if (!kv) return null;
  try {
    return await kv.get<EventDraft>(key(slug, locale), "json");
  } catch {
    // A draft that cannot be read must never take a page down with it. The
    // committed JSON is a complete, correct answer on its own; this store only
    // ever adds to it.
    return null;
  }
}

export async function writeDraft(
  slug: string,
  locale: string,
  draft: EventDraft,
): Promise<boolean> {
  const kv = await store();
  if (!kv) return false;
  await kv.put(key(slug, locale), JSON.stringify(draft));
  return true;
}

export async function clearDraft(slug: string, locale: string): Promise<void> {
  const kv = await store();
  await kv?.delete(key(slug, locale));
}
