/**
 * Events / "Активности" — data layer.
 *
 * Source of truth is the committed JSON generated from Notion by
 * `npm run sync:events`. A deploy never reads Notion and never needs its token;
 * events change only after somebody requests a sync and commits the result.
 *
 * Bilingual: every human-facing string carries `bg` + `en`. `getEvents(locale)`
 * / `getEvent(locale, slug)` return already-localized `BdcEvent`s so components
 * stay locale-agnostic.
 */
import type { Locale } from "./i18n";
import { locales } from "./i18n";
// Generated by `npm run sync:events`.
import generatedEvents from "./events.generated.json";
// Staging-only overlay; a no-op returning null on the apex. See lib/drafts.ts.
import { readDraft } from "./drafts";

/* =============================================================================
   Types
============================================================================= */

/** One cover image, with the proportions the gallery needs to lay it out. */
/**
 * A picture in an event's gallery.
 *
 * `alt` comes from the image's caption in Notion, where an editor writes it in
 * both languages (see captionAlt in scripts/sync-notion-events.mjs). It is
 * optional because most events predate the convention, and null-when-absent
 * rather than "" on purpose: "" asserts a photograph is decorative, which is
 * a claim, not a sensible default for a picture someone chose to publish.
 */
export type EventImage = {
  src: string;
  width: number;
  height: number;
  alt?: { bg: string; en: string } | null;
};

/** A localized event, ready to render. */
export type BdcEvent = {
  slug: string;
  /** ISO date (YYYY-MM-DD) — used for sorting only. */
  date: string;
  /** "25.04" — list column. */
  dateShort: string;
  /** "25.04.2026" — overlay meta. */
  dateLong: string;
  /** Localized title. */
  name: string;
  /** Localized type label + its brand accent colour. */
  type: { label: string; accent: string };
  /** Localized description (overlay body). */
  description: string;
  /**
   * Where it happened, verbatim from Notion ("Toplocentrala, Sofia"). Nothing
   * renders it, but schema.org/Event wants a location and inventing one would
   * be worse than omitting it. Empty string for online events.
   */
  location: string;
  /**
   * Cover images (overlay). Empty for most rows; the list never uses them.
   * An array because a Notion "Hero-image" cell holds several files, and two
   * or more of them switches the overlay to its gallery layout.
   *
   * Intrinsic dimensions travel with each one. The gallery gives every slide
   * the same height and lets its width follow the picture, so it needs the
   * real proportions up front — sizing them from a fixed box instead would
   * crop the sides off anything that is not exactly the frame's shape.
   */
  covers: EventImage[];
};

/**
 * Event-type key → accent colour + bilingual label. Extend as new types appear.
 *
 * The first four mirror Notion's "Формат" select, which is the only
 * categorising column the Събития tab has — so it is what the third column of
 * the list shows. The rest predate the Notion wiring and are kept for the
 * older content types retained for compatibility with committed rows.
 */
const TYPE_META = {
  live: { accent: "var(--bdc-tomato)", label: { bg: "На живо", en: "In person" } },
  online: { accent: "var(--bdc-lavender)", label: { bg: "Онлайн", en: "Online" } },
  hybrid: { accent: "var(--bdc-orange)", label: { bg: "Хибридно", en: "Hybrid" } },
  result: { accent: "var(--bdc-indigo)", label: { bg: "Резултат", en: "Result" } },
  conference: { accent: "var(--bdc-tomato)", label: { bg: "Конференция", en: "Conference" } },
  workshop: { accent: "var(--bdc-orange)", label: { bg: "Работилница", en: "Workshop" } },
  lecture: { accent: "var(--bdc-lavender)", label: { bg: "Лекция", en: "Lecture" } },
  award: { accent: "var(--bdc-amber)", label: { bg: "Награда", en: "Award" } },
  meeting: { accent: "var(--bdc-burgundy)", label: { bg: "Среща", en: "Meeting" } },
} as const;

type EventType = keyof typeof TYPE_META;

/** Raw, un-localized event as stored in the generated JSON. */
type RawEvent = {
  slug: string;
  date: string; // ISO YYYY-MM-DD
  type: EventType;
  name: Record<Locale, string>;
  description: Record<Locale, string>;
  location?: string;
  covers?: EventImage[];
  /**
   * Notion's last_edited_time (date part), stamped by the sync — the one real
   * modification date this site holds, and the only thing the sitemap is
   * allowed to say `lastmod` with. Optional because rows synced before the
   * field existed do not carry it; they simply say nothing.
   */
  lastEdited?: string;
};

/**
 * Editorial removals now happen in Notion, not here.
 *
 * This set once hid a withdrawn assembly portrait by filename. Two things
 * ended that approach: the photograph was removed from the Notion gallery
 * itself (the correct, permanent fix — the sync can never bring back what
 * its source no longer holds), and image files are now named by a hash of
 * their content, so a filename written here would not survive the next
 * sync anyway. If a picture must ever be withdrawn again: delete it from
 * the event's "Images to be used:" section in Notion and re-run the sync.
 * The set stays as the seam where a render-side exclusion would go if an
 * emergency ever demands one faster than a sync.
 */
const HIDDEN_EVENT_COVERS = new Set<string>([]);

/** The synced rows. */
const GENERATED: RawEvent[] = (generatedEvents.events ?? []).map((e) => ({
  slug: e.slug,
  date: e.date,
  type: e.type as EventType,
  name: e.name as Record<Locale, string>,
  description: e.description as Record<Locale, string>,
  location: e.location ?? "",
  // Downloaded from the row's "Hero-image" by the sync and committed under
  // public/figma/events — a Notion file URL is signed and expires in an hour,
  // so it cannot be baked into a static build. Rows without any are the norm;
  // the overlay simply opens on its title.
  covers: (e as { covers?: EventImage[] }).covers?.filter(
    ({ src }) => !HIDDEN_EVENT_COVERS.has(src),
  ),
  lastEdited: (e as { lastEdited?: string }).lastEdited,
}));

/* =============================================================================
   Localization + formatting
============================================================================= */

/**
 * Venue names that need saying differently in English.
 *
 * `Локация` is a single Notion column, not a bilingual pair, so whatever an
 * editor types appears on both sites. Most values need nothing — "Barter,
 * Sofia", "Toplocentrala, Sofia", "SOHO, Sofia, Bulgaria" are already the names
 * those places go by in either language. Two are Bulgarian abbreviations that
 * an English reader cannot expand, and left alone they put Cyrillic on three of
 * the eight English event pages.
 *
 * Deliberately a lookup of exact strings rather than a transliterator:
 * "НБУ, София" is not New Bulgarian University because of its letters, it is
 * because that is the institution. A transliterator would produce "NBU, Sofia"
 * and think it had done the job. An unmapped value falls through unchanged,
 * which is the right failure — a venue name in its own language beats a
 * mangled one.
 */
const LOCATION_EN: Record<string, string> = {
  "НБУ, София": "New Bulgarian University, Sofia",
  "БДС Офис": "Bulgarian Design Council Office",
};

/** "2026-04-25" → { short: "25.04", long: "25.04.2026" } (locale-neutral, numeric). */
function formatDate(iso: string): { short: string; long: string } {
  const [y, m, d] = iso.split("-");
  return { short: `${d}.${m}`, long: `${d}.${m}.${y}` };
}

function localize(raw: RawEvent, locale: Locale): BdcEvent {
  const { short, long } = formatDate(raw.date);
  const meta = TYPE_META[raw.type];
  return {
    slug: raw.slug,
    date: raw.date,
    dateShort: short,
    dateLong: long,
    name: raw.name[locale],
    type: { label: meta.label[locale], accent: meta.accent },
    description: raw.description[locale],
    location:
      locale === "en" && raw.location
        ? LOCATION_EN[raw.location] ?? raw.location
        : raw.location ?? "",
    covers: raw.covers ?? [],
  };
}

/** Newest first. */
function byDateDesc(a: RawEvent, b: RawEvent) {
  return a.date < b.date ? 1 : a.date > b.date ? -1 : 0;
}

/* =============================================================================
   Public API
============================================================================= */

/** All committed events for a locale, newest first. */
export async function getEvents(locale: Locale): Promise<BdcEvent[]> {
  const raw = fetchRawEvents().slice().sort(byDateDesc);
  return raw.map((e) => localize(e, locale));
}

/**
 * One event by slug, or null.
 *
 * On staging a draft — copy edited in the browser with Shift+E — is layered on
 * top of the committed JSON, so an edit is visible the moment it is saved
 * rather than after the next Notion sync and redeploy. On the apex
 * `readDraft()` returns null unconditionally and this is the same function it
 * always was; see lib/drafts.ts for why that is enforced in two places.
 */
export async function getEvent(locale: Locale, slug: string): Promise<BdcEvent | null> {
  const raw = fetchRawEvents().find((e) => e.slug === slug);
  if (!raw) return null;
  const event = localize(raw, locale);

  const draft = await readDraft(slug, locale);
  if (!draft) return event;

  return {
    ...event,
    description: draft.description,
    // Only the covers the editor actually described change. A cover missing
    // from `alts` keeps whatever shipped with it, so saving a draft that
    // touches one photograph cannot blank the alt text on the other six.
    covers: event.covers.map((c) =>
      draft.alts[c.src]
        ? { ...c, alt: { ...(c.alt ?? { bg: "", en: "" }), [locale]: draft.alts[c.src] } }
        : c,
    ),
  };
}

/**
 * Slug list for `generateStaticParams`. Locale-neutral (slugs are shared across
 * locales), so both the full page and the intercepted modal prerender the same
 * set under each `[locale]`.
 */
export async function getEventSlugs(): Promise<{ slug: string; lastEdited?: string }[]> {
  return fetchRawEvents().map((e) => ({ slug: e.slug, lastEdited: e.lastEdited }));
}

/** Locales this module knows about (re-export for callers building param grids). */
export { locales };

function fetchRawEvents(): RawEvent[] {
  if (GENERATED.length > 0) return GENERATED;
  // The sync itself refuses to write an empty list. If this invariant is ever
  // broken by hand, fail the build instead of silently publishing invented
  // mock events or an empty activities section.
  throw new Error(
    "lib/events.generated.json contains no events. Run npm run sync:events; do not hand-edit it.",
  );
}
