/**
 * Events / "Активности" — data layer.
 *
 * Source of truth is a Notion database (build-time fetch: events refresh when
 * CI redeploys, not per request). The Notion integration isn't wired yet, so
 * `getEvents` falls back to the typed MOCK below whenever `NOTION_TOKEN` /
 * `NOTION_EVENTS_DB` are absent or a fetch fails — the build never breaks.
 *
 * Bilingual: every human-facing string carries `bg` + `en`. `getEvents(locale)`
 * / `getEvent(locale, slug)` return already-localized `BdcEvent`s so components
 * stay locale-agnostic.
 *
 * To go live, see the "NOTION WIRING" block near the bottom.
 */
import type { Locale } from "./i18n";
import { locales } from "./i18n";
// Generated by `npm run sync:events` — see the note in fetchRawEvents.
import generatedEvents from "./events.generated.json";
// Staging-only overlay; a no-op returning null on the apex. See lib/drafts.ts.
import { readDraft } from "./drafts";

/* =============================================================================
   Types
============================================================================= */

/** One cover image, with the proportions the gallery needs to lay it out. */
/**
 * A picture in an event's gallery.
 *
 * `alt` comes from the image's caption in Notion, where an editor writes it in
 * both languages (see captionAlt in scripts/sync-notion-events.mjs). It is
 * optional because most events predate the convention, and null-when-absent
 * rather than "" on purpose: "" asserts a photograph is decorative, which is
 * a claim, not a sensible default for a picture someone chose to publish.
 */
export type EventImage = {
  src: string;
  width: number;
  height: number;
  alt?: { bg: string; en: string } | null;
};

/** A localized event, ready to render. */
export type BdcEvent = {
  slug: string;
  /** ISO date (YYYY-MM-DD) — used for sorting only. */
  date: string;
  /** "25.04" — list column. */
  dateShort: string;
  /** "25.04.2026" — overlay meta. */
  dateLong: string;
  /** Localized title. */
  name: string;
  /** Localized type label + its brand accent colour. */
  type: { label: string; accent: string };
  /** Localized description (overlay body). */
  description: string;
  /**
   * Where it happened, verbatim from Notion ("Toplocentrala, Sofia"). Nothing
   * renders it, but schema.org/Event wants a location and inventing one would
   * be worse than omitting it. Empty string for online events.
   */
  location: string;
  /**
   * Cover images (overlay). Empty for most rows; the list never uses them.
   * An array because a Notion "Hero-image" cell holds several files, and two
   * or more of them switches the overlay to its gallery layout.
   *
   * Intrinsic dimensions travel with each one. The gallery gives every slide
   * the same height and lets its width follow the picture, so it needs the
   * real proportions up front — sizing them from a fixed box instead would
   * crop the sides off anything that is not exactly the frame's shape.
   */
  covers: EventImage[];
};

/**
 * Event-type key → accent colour + bilingual label. Extend as new types appear.
 *
 * The first three mirror Notion's "Формат" select, which is the only
 * categorising column the Събития tab has — so it is what the third column of
 * the list shows. The rest predate the Notion wiring and are kept for the
 * fallback rows below.
 */
const TYPE_META = {
  live: { accent: "var(--bdc-tomato)", label: { bg: "На живо", en: "In person" } },
  online: { accent: "var(--bdc-lavender)", label: { bg: "Онлайн", en: "Online" } },
  hybrid: { accent: "var(--bdc-orange)", label: { bg: "Хибридно", en: "Hybrid" } },
  conference: { accent: "var(--bdc-tomato)", label: { bg: "Конференция", en: "Conference" } },
  workshop: { accent: "var(--bdc-orange)", label: { bg: "Работилница", en: "Workshop" } },
  lecture: { accent: "var(--bdc-lavender)", label: { bg: "Лекция", en: "Lecture" } },
  award: { accent: "var(--bdc-amber)", label: { bg: "Награда", en: "Award" } },
  meeting: { accent: "var(--bdc-burgundy)", label: { bg: "Среща", en: "Meeting" } },
} as const;

type EventType = keyof typeof TYPE_META;

/** Raw, un-localized event as stored in mock / mapped from Notion. */
type RawEvent = {
  slug: string;
  date: string; // ISO YYYY-MM-DD
  type: EventType;
  name: Record<Locale, string>;
  description: Record<Locale, string>;
  location?: string;
  covers?: EventImage[];
};

/** The synced rows. */
const GENERATED: RawEvent[] = (generatedEvents.events ?? []).map((e) => ({
  slug: e.slug,
  date: e.date,
  type: e.type as EventType,
  name: e.name as Record<Locale, string>,
  description: e.description as Record<Locale, string>,
  location: e.location ?? "",
  // Downloaded from the row's "Hero-image" by the sync and committed under
  // public/figma/events — a Notion file URL is signed and expires in an hour,
  // so it cannot be baked into a static build. Rows without any are the norm;
  // the overlay simply opens on its title.
  covers: (e as { covers?: EventImage[] }).covers,
}));

/* =============================================================================
   MOCK — shape mirrors the intended Notion rows. Replace via NOTION WIRING.
============================================================================= */
const MOCK: RawEvent[] = [
  {
    slug: "icod-regional-meeting-2026",
    date: "2026-04-25",
    type: "conference",
    name: {
      bg: "Regional Meeting of the International Council of Design (ICoD)",
      en: "Regional Meeting of the International Council of Design (ICoD)",
    },
    description: {
      bg: "Организирана от UX Bulgaria, със специален гост Зинаида Илер, работилницата събра студенти от различни специалности в New Bulgarian University, за да се запознаят с UX процеса.",
      en: "Organized by UX Bulgaria with special guest Zinaida Iller, the workshop brought together students from different disciplines at New Bulgarian University to get acquainted with the UX process.",
    },
    location: "",
    covers: [{ src: "/figma/event-cover.png", width: 1600, height: 1200 }],
  },
  {
    slug: "pechakucha-night-sofia-42",
    date: "2026-03-18",
    type: "conference",
    name: { bg: "PechaKucha Night Sofia #42", en: "PechaKucha Night Sofia #42" },
    description: {
      bg: "Вечер на бързи, вдъхновяващи презентации по формата 20×20 — двадесет кадъра, всеки по двадесет секунди — с говорители от дизайна, архитектурата и технологиите.",
      en: "An evening of fast, inspiring 20×20 talks — twenty slides, twenty seconds each — with speakers from design, architecture and technology.",
    },
    location: "",
    covers: [{ src: "/figma/event-cover.png", width: 1600, height: 1200 }],
  },
  {
    slug: "future-makers-lab-workshop",
    date: "2026-02-14",
    type: "workshop",
    name: { bg: "Future Makers Lab: системно мислене", en: "Future Makers Lab: systems thinking" },
    description: {
      bg: "Практическа работилница за юноши, която развива системно мислене, проблемно рамкиране и отговорна работа с AI.",
      en: "A hands-on workshop for teenagers building systems thinking, problem framing and responsible work with AI.",
    },
    location: "",
    covers: [{ src: "/figma/event-cover.png", width: 1600, height: 1200 }],
  },
  {
    slug: "design-for-good-awards",
    date: "2026-01-30",
    type: "award",
    name: { bg: "Дизайн за Добро — награди", en: "Design for Good — Awards" },
    description: {
      bg: "БДС връчи три награди „Дизайн за добро“ на първия Студентски дизайн маратон в НБУ, отличавайки идеи, в които дизайнът е инструмент за смислена промяна.",
      en: "The BDC awarded three „Design for Good“ prizes at the first Student Design Marathon at NBU, recognizing ideas in which design is a tool for meaningful change.",
    },
    location: "",
    covers: [{ src: "/figma/event-cover.png", width: 1600, height: 1200 }],
  },
];

/* =============================================================================
   Localization + formatting
============================================================================= */

/**
 * Venue names that need saying differently in English.
 *
 * `Локация` is a single Notion column, not a bilingual pair, so whatever an
 * editor types appears on both sites. Most values need nothing — "Barter,
 * Sofia", "Toplocentrala, Sofia", "SOHO, Sofia, Bulgaria" are already the names
 * those places go by in either language. Two are Bulgarian abbreviations that
 * an English reader cannot expand, and left alone they put Cyrillic on three of
 * the eight English event pages.
 *
 * Deliberately a lookup of exact strings rather than a transliterator:
 * "НБУ, София" is not New Bulgarian University because of its letters, it is
 * because that is the institution. A transliterator would produce "NBU, Sofia"
 * and think it had done the job. An unmapped value falls through unchanged,
 * which is the right failure — a venue name in its own language beats a
 * mangled one.
 */
const LOCATION_EN: Record<string, string> = {
  "НБУ, София": "New Bulgarian University, Sofia",
  "БДС Офис": "Bulgarian Design Council Office",
};

/** "2026-04-25" → { short: "25.04", long: "25.04.2026" } (locale-neutral, numeric). */
function formatDate(iso: string): { short: string; long: string } {
  const [y, m, d] = iso.split("-");
  return { short: `${d}.${m}`, long: `${d}.${m}.${y}` };
}

function localize(raw: RawEvent, locale: Locale): BdcEvent {
  const { short, long } = formatDate(raw.date);
  const meta = TYPE_META[raw.type];
  return {
    slug: raw.slug,
    date: raw.date,
    dateShort: short,
    dateLong: long,
    name: raw.name[locale],
    type: { label: meta.label[locale], accent: meta.accent },
    description: raw.description[locale],
    location:
      locale === "en" && raw.location
        ? LOCATION_EN[raw.location] ?? raw.location
        : raw.location ?? "",
    covers: raw.covers ?? [],
  };
}

/** Newest first. */
function byDateDesc(a: RawEvent, b: RawEvent) {
  return a.date < b.date ? 1 : a.date > b.date ? -1 : 0;
}

/* =============================================================================
   Public API
============================================================================= */

/** All events for a locale, newest first. Notion when configured, else MOCK. */
export async function getEvents(locale: Locale): Promise<BdcEvent[]> {
  const raw = (await fetchRawEvents()).slice().sort(byDateDesc);
  return raw.map((e) => localize(e, locale));
}

/**
 * One event by slug, or null.
 *
 * On staging a draft — copy edited in the browser with Shift+E — is layered on
 * top of the committed JSON, so an edit is visible the moment it is saved
 * rather than after the next Notion sync and redeploy. On the apex
 * `readDraft()` returns null unconditionally and this is the same function it
 * always was; see lib/drafts.ts for why that is enforced in two places.
 */
export async function getEvent(locale: Locale, slug: string): Promise<BdcEvent | null> {
  const raw = (await fetchRawEvents()).find((e) => e.slug === slug);
  if (!raw) return null;
  const event = localize(raw, locale);

  const draft = await readDraft(slug, locale);
  if (!draft) return event;

  return {
    ...event,
    description: draft.description,
    // Only the covers the editor actually described change. A cover missing
    // from `alts` keeps whatever shipped with it, so saving a draft that
    // touches one photograph cannot blank the alt text on the other six.
    covers: event.covers.map((c) =>
      draft.alts[c.src]
        ? { ...c, alt: { ...(c.alt ?? { bg: "", en: "" }), [locale]: draft.alts[c.src] } }
        : c,
    ),
  };
}

/**
 * Slug list for `generateStaticParams`. Locale-neutral (slugs are shared across
 * locales), so both the full page and the intercepted modal prerender the same
 * set under each `[locale]`.
 */
export async function getEventSlugs(): Promise<{ slug: string }[]> {
  return (await fetchRawEvents()).map((e) => ({ slug: e.slug }));
}

/** Locales this module knows about (re-export for callers building param grids). */
export { locales };

/* =============================================================================
   NOTION WIRING — build-time fetch. Currently returns MOCK.

   To go live:
   1. In Notion, create an internal integration and copy its secret.
   2. Share the events database with that integration.
   3. Set build-time env vars (locally in `.env`, and as GitHub Actions secrets
      for the deploy workflow):
        NOTION_TOKEN=secret_xxx
        NOTION_EVENTS_DB=<database id>
   4. Adjust PROP below to match your Notion property names, and confirm the
      types (Title, Date, Select, Rich text, Files). Then replace the MOCK
      return in `fetchRawEvents` with `fetchNotionEvents()`.

   Kept as a documented stub so the build stays green until the DB is ready.
============================================================================= */

// Expected Notion property names — EDIT to match the real database.
// (Bilingual fields assume separate BG/EN columns.)
const PROP = {
  nameBg: "Name (BG)",
  nameEn: "Name (EN)",
  date: "Date",
  type: "Type", // a Select whose options map to TYPE_META keys
  descBg: "Description (BG)",
  descEn: "Description (EN)",
  cover: "Cover",
  slug: "Slug",
} as const;

async function fetchRawEvents(): Promise<RawEvent[]> {
  // Committed JSON first — same arrangement as the team bios: an editor runs
  // the sync on their own machine and commits the result, so no Notion token
  // ever reaches CI or the Worker (this repo is public). A live fetch is still
  // honoured when the env vars happen to be set, and MOCK is the last resort so
  // the build can never go dark.
  if (GENERATED.length > 0) return GENERATED;

  const token = process.env.NOTION_TOKEN;
  const db = process.env.NOTION_EVENTS_DB;
  if (!token || !db) return MOCK; // not configured yet → mock

  try {
    return await fetchNotionEvents(token, db);
  } catch (err) {
    console.warn("[events] Notion fetch failed, falling back to mock:", err);
    return MOCK;
  }
}

async function fetchNotionEvents(token: string, db: string): Promise<RawEvent[]> {
  const res = await fetch(`https://api.notion.com/v1/databases/${db}/query`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Notion-Version": "2022-06-28",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ sorts: [{ property: PROP.date, direction: "descending" }] }),
  });
  if (!res.ok) throw new Error(`Notion ${res.status}`);
  const data = (await res.json()) as { results: NotionPage[] };
  return data.results.map(mapNotionPage).filter((e): e is RawEvent => e !== null);
}

/* Minimal Notion shapes — only the property kinds we read. */
type RichText = { plain_text: string }[];
// Discriminated on `type`; only the property kinds we read are modelled — any
// other Notion property type simply won't match our `.type ===` guards.
type NotionProp =
  | { type: "title"; title: RichText }
  | { type: "rich_text"; rich_text: RichText }
  | { type: "date"; date: { start: string } | null }
  | { type: "select"; select: { name: string } | null }
  | { type: "files"; files: { file?: { url: string }; external?: { url: string } }[] };
type NotionPage = { properties: Record<string, NotionProp> };

function plain(p?: NotionProp): string {
  if (!p) return "";
  if (p.type === "title") return p.title.map((t) => t.plain_text).join("");
  if (p.type === "rich_text") return p.rich_text.map((t) => t.plain_text).join("");
  return "";
}

function mapNotionPage(page: NotionPage): RawEvent | null {
  const props = page.properties;

  const dateProp = props[PROP.date];
  const date = dateProp?.type === "date" ? dateProp.date?.start ?? "" : "";

  const typeProp = props[PROP.type];
  const typeName = typeProp?.type === "select" ? typeProp.select?.name ?? "" : "";
  const type = (typeName.toLowerCase() as EventType) in TYPE_META
    ? (typeName.toLowerCase() as EventType)
    : "conference";
  const nameBg = plain(props[PROP.nameBg]);
  const nameEn = plain(props[PROP.nameEn]) || nameBg;
  if (!date || !nameBg) return null; // skip incomplete rows

  const filesProp = props[PROP.cover];
  // Every file in the cell, not just the first: two or more is what puts the
  // overlay into its gallery layout.
  // The live path has no way to know a remote file's proportions without
  // fetching it, so these fall back to the frame's own shape. Only the
  // committed JSON (the path actually used) carries real dimensions.
  const covers: EventImage[] =
    filesProp?.type === "files"
      ? filesProp.files
          .map((f) => f.file?.url ?? f.external?.url)
          .filter((u): u is string => !!u)
          .map((src) => ({ src, width: 732, height: 540 }))
      : [];

  const slug = plain(props[PROP.slug]) || slugify(nameEn);

  return {
    slug,
    date: date.slice(0, 10),
    type,
    name: { bg: nameBg, en: nameEn },
    description: {
      bg: plain(props[PROP.descBg]),
      en: plain(props[PROP.descEn]) || plain(props[PROP.descBg]),
    },
    // The live path has no Локация mapping; the committed JSON is the path
    // actually used, and it does.
    location: "",
    covers,
  };
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}
